### ISSUE TITLE
`undefined reference` in boost filesystem from release 1.68 for gcc 5.2-6.3

### ISSUE THREAD

**Issue by andrejnau** [boostorg/filesystem#83]
After update boost from 1.67 to 1.68 our code can't be linked.

Here simple code: https://wandbox.org/permlink/MKhgrdMO1p1aHEOn
```/tmp/ccXDdraA.o: In function `boost::system::generic_category()':
prog.cc:(.text._ZN5boost6system16generic_categoryEv[_ZN5boost6system16generic_categoryEv]+0x5): undefined reference to `boost::system::detail::generic_category_instance'
collect2: error: ld returned 1 exit status```

P.S.
Can you test others boost component? I think this is not the only problem in this release.

**Comment by jbeich** [comment]
Probably, duplicate. See
https://github.com/boostorg/system/issues/24
https://github.com/boostorg/system/issues/26

**Comment by wkailey** [comment]
I just installed boost 1.68, and I have the same problem. After successfully untarring, building, and installing boost, I am including <boost/regex.hpp> and linking with -lboost_regex, and it comes up with an undefined external [a function named . . . <long bunch of template paramteters> . . .match()] at line 386 of regex/v4/perl_matcher.hpp

**Comment by jcbritobr** [comment]
This also happens to me with mingw 64 builds on windows and gcc 7.x

**Comment by pdimov** [comment]
It might be a good idea to check 1.69 RC1 at https://dl.bintray.com/boostorg/release/1.69.0/source/

Boost.System is header-only in 1.69, so the link error in the original post should no longer be an issue.

But in general, the rule is that you have to build Boost with the same C++ standard with which you'll be using it. If you're going to use f.ex. C++14, and you're building with a compiler for which C++14 isn't default (such as gcc 5/clang 5 or earlier) you need to build with `b2 cxxstd=14`.

**Comment by pdimov** [comment]
And it failed. -)

**Comment by Lastique** [comment]
For a different reason. :)

**Comment by jcbritobr** [comment]
> 
> 
> It might be a good idea to check 1.69 RC1 at https://dl.bintray.com/boostorg/release/1.69.0/source/
> 
> Boost.System is header-only in 1.69, so the link error in the original post should no longer be an issue.
> 
> But in general, the rule is that you have to build Boost with the same C++ standard with which you'll be using it. If you're going to use f.ex. C++14, and you're building with a compiler for which C++14 isn't default (such as gcc 5/clang 5 or earlier) you need to build with `b2 cxxstd=14`.

I was using gcc 7.3, but will build it again, using b2 cxxstd=14.

Thank you guys.

**Comment by Lastique** [comment]
The tests are [passing](https://ci.appveyor.com/project/Lastique/filesystem/builds/20871761/job/4iqxa56sr2sr4685) now. So either this was an ABI mismatch or it was already fixed in develop.
